### ISSUE TITLE
Consider using `go doc` for `M-x godoc`

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-mode.el#101]
`go doc` provides a superior way of searching for identifiers, so it might make sense to use it instead of `godoc`. On the other hand, people might rely on the current behaviour of `godoc`. Feedback welcome.

**Comment by psanford** [comment]
I find the current implementation using `godoc` often insufficient. One thing I often want is to be able to get docs on a single method instead of the whole package (i.e. `godoc encoding/json Unmarshal`).  With the current implementation using `(godoc--read-query)` you can't specify a method because the minibuffer prompt doesn't allow spaces. With `go doc` you could specify `encoding/json.Unmarshal` while still maintaining the existing behavior of being able to use `(completing-read)` to complete package names.

Either way, I think it makes sense to move the command name into a customizable variable: `godoc-command`.

**Comment by dominikh** [comment]
We should definitely fix the auto-completion/space issue, regardless of godoc vs go doc. The commands should support the entire range of inputs allowed by the tools, completion shouldn't get in the way.

**Comment by dominikh** [comment]
Not being able to type spaces isn't our fault, but that of Emacs, and there are various ways of avoiding the issue:

- Use C-q SPC to insert a space character
- Change the key map so that SPC inserts a space and doesn't attemt completion

```
 (define-key minibuffer-local-completion-map
             " " 'self-insert-command))
 (define-key minibuffer-local-must-match-map
             " " 'self-insert-command))
```

See https://lists.gnu.org/archive/html/help-gnu-emacs/2008-03/msg00164.html for more information regarding that.


I'm currently considering two new variables: `godoc-command`, like you suggested, and one for disabling completion in `M-x godoc` alltogether. With `go doc`, completion becomes a lot less useful, and potentially more annoying due to the issue with typing spaces. We'd default `godoc-command` to `go doc` and completion to disabled. Any thoughts on this?

**Comment by psanford** [comment]
That sounds good to me.

**Comment by bassu** [comment]
@dominikh I concur sir! Using `go doc` is much saner than `godoc`.
For instance, `go doc http.cookie` is much much better than `godoc net/http Cookie`.

 But include both since there are things that the prior cannot do.

**Comment by iced** [comment]
godoc doesn't work for me - e.g.:

godoc: doc: import "/usr/local/Cellar/go/1.6/libexec/src/log/": cannot import absolute path

**Comment by dominikh** [comment]
@iced Please open a new issue, and include the following information in it:

- the value of godoc-command (if the variable exists)
- the exact command and input you used
- the output of `go env GOROOT` and `ls $(go env GOROOT)` in a shell
