### ISSUE TITLE
go-gb-gopath false positive?

### ISSUE THREAD

**Issue by peter-mogensen** [dominikh/go-mode.el#166]
I have some non-gb projects which contain both a "src" and a "vendor" folder at the top level. They are just standard go tool projects using GO15VENDOREXPERIMENT vendoring. (no "src" folder inside "vendor")
But go-guess-gopath detects them as go-gb-gopath projects.
Wouldn't go-gb-gopath be more precise without sacrificing correctness wrt. the gb specification if it tested whether the detected "vendor" folder contained a "src" folder? As in

/proj/src
/proj/vendor/src

Of course... gb projects don't need to have a vendor folder, but then there would also be no harm for go-plain-gopath to just return GOPATH=/proj

**Comment by dominikh** [comment]
GO15VENDOREXPERIMENT requires that `vendor` lives somewhere beneath `src`, not alongside it, so I'm not sure I quite understand your directory layout.

**Comment by peter-mogensen** [comment]
It's like:
/proj/vendir
/proj/src/
/proj/src/package/name -> ../..

So wrt. "package/name" vendor des live below "src"

**Comment by dominikh** [comment]
Assuming `GOPATH=/proj`, that's not a valid vendor set up. And if GOPATH is a parent of `/proj`, you probably shouldn't have another `src` directory.

**Comment by peter-mogensen** [comment]
However... using a symlink does break some times where tools assume there's no symlinks... as in this code from go-mode.el:
```elisp
(call-process-region (point-min)
                               (point-max)
                               godef-command
                               nil
                               outbuf
                               nil
                               "-i"
                               "-t"
                               "-f"
                               (file-truename (buffer-file-name (go--coverage-origin-buffer)))
                               "-o"
                               (number-to-string (go--position-bytes point)))
```

... where the use of "file-truename" expands the symlink. ...
Is there any need for using file-truename ? ... I'm not sure whether buffer-file-name can ever be relative, but wouldn't expand-file-name be enough?

**Comment by peter-mogensen** [comment]
GOPATH=/proj
But what makes that not a valid vendor setup?
"go build package/name" works as intented.

**Comment by dominikh** [comment]
Because vendored packages need to be beneath the `src/` tree. And `/proj/vendor/` is clearly not beneath `/proj/src` – if it does compile, it is probably picking up the dependencies from somewhere else in your GOPATH, not from `vendor`. See https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/ for the specifics of the layout and how vendored dependencies are resolved.

As for symlinks: Using symlinks inside GOPATH is discouraged/not supported by the official tools, and thus not supported by us, either. We resolve symlinks for the case where GOPATH itself is a symlink, i.e. `GOPATH=/foo` and `/foo -> /bar`. If we didn't resolve them, we may end up with different paths, depending on the tools used, and which path the user used in Emacs to open the file.

**Comment by peter-mogensen** [comment]
Hmm... vendor is resolved as /proj/src/package/name/vendor ... which is why it works.

Anyway.... a project where `/proj/vendor` has no `src` is not a gb project, right?

**Comment by dominikh** [comment]
It's a gb project with no vendored dependencies yet. Not that it matters, the detection doesn't conflict with any other tool. It's either a gb project, or nothing at all.

I'm going to close this issue as there is nothing to do.
