### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by aaronbee** [dominikh/go-mode.el#181]
It's been a while since go-mode has tagged a release, hence it has been a while since MELPA stable has offered an update. Do you plan on tagging newer releases or should I fetch updates to go-mode from non-stable MELPA?

**Comment by dominikh** [comment]
I've just pushed v1.5.0. I do intend to tag regularly, I just didn't think that much interesting had happened since 1.4.0.

**Comment by aaronbee** [comment]
Thanks! The change I cared about most since v1.4.0 was go-guru.el being added.

**Comment by dominikh** [comment]
@aaronbee Oh. I'm not sure if this tag is going to help you, then. Haven't really found the time to properly integrate guru and rename since they've been merged. In particular, their metadata isn't quite right, with versions that do not match the git tag. I'm not sure if MELPA stable will handle that correctly or not.
