### ISSUE TITLE
Multiline if indentation 

### ISSUE THREAD

**Issue by kostafey** [dominikh/go-mode.el#234]
More indentation then expected for closing curve bracket in multiline if statement.
Expected:
```golang
if someFn(
	firstParam,
	secondParam) {
		print()
}
```
Actual:
```golang
if someFn(
	firstParam,
	secondParam) {
		print()
	}
```

**Comment by dominikh** [comment]
Yup, that's a bug. But I'm not likely to fix that in the foreseeable future, for two reasons: 

1. that style of code is rare to begin with
2. it probably requires substantial changes to the algorithm

This is a bit of a cop out, but the recommended way of formatting this code is:

	if someFn(
		firstParam,
		secondParam,
	) {
		print()
	}

This is because your "expected" example isn't what gofmt would produce. For your code, gofmt formats it as 

	if someFn(
		firstParam,
		secondParam) {
		print()
	}

which makes it hard to tell where the condition ends and the if body begins.
