### ISSUE TITLE
Make go formatting behavior local to go-mode.

### ISSUE THREAD

**Issue by phiryll** [dominikh/go-mode.el#245]
Can tab/space and indent behavior be done in a way that doesn't impact every non-Go file I edit? I'm now considering distinct emacs configs (and running emacs instances) for editing Go code and everything else, which is seriously ugly.

If there's a way to do this that I've missed, can you please update the README with instructions?

**Comment by dominikh** [comment]
go-mode doesn't affect any of your settings outside of Go buffers.

**Comment by phiryll** [comment]
I think I figured out my problem. After installing the go-mode package (and go-autocomplete, go-errcheck, go-impl, go-eldoc), this line in my .emacs stopped working, for all file types/modes:

`(setq indent-tabs-mode nil)`

After some digging, I discovered that changing `setq` to `setq-default` does work. I now understand why this works, but am a little dismayed that I've been using just `setq` for this variable since the 90's with no problems, and adding these packages changed that.

It might be that `(package-initialize)` being added to the top of my .emacs, before setting `indent-tabs-mode`, had something to do with this?

**Comment by dominikh** [comment]
I honestly cannot tell you why that is. Using setq for it should've never worked, since it makes the variable buffer local. It is worth pointing out that a lot of modes, such as ruby-mode, perl-mode and c-mode automatically indent with spaces instead of tabs. Loading go-mode should, however, have no effect on that, either. It sets the variable local to Go buffers.
