### ISSUE TITLE
Flycheck: Suspicious state from syntax checker go-vet

### ISSUE THREAD

**Issue by yuanlai** [dominikh/go-mode.el#324]
When I import native package into native test file.
```
package tests

import (
    ...
    "github.com/myGithubProjectRootPath/internal/platform/web"
)

...
```
It report a import package path not allowed error.
> Suspicious state from syntax checker go-vet: Flycheck checker go-vet returned non-zero exit code 1, but its output contained no errors: package command-line-arguments (test) 

> imports github.com/myGithubProjectRootPath/internal/platform/web: use of internal package github.com/myGithubProjectRootPath/internal/platform/web not allowed

> Try installing a more recent version of go-vet, and please open a bug report if the issue persists in the latest release.  Thanks!

The tests.go under `myGithubProjectRootPath/cmd/user-api/tests` directory.

**Comment by psanford** [comment]
This doesn't look like a go-mode issue, it looks like it is possibly an issue with flycheck or just an issue with your environment. go-mode does not have any integration with flycheck or go vet directly. 

I'd suggest you try running go vet from the command line on the file to see what error it reports. If you think the issue is with flycheck and not your environment you should open an issue with that project.
