### ISSUE TITLE
Need someway to custom gofmt error window height

### ISSUE THREAD

**Issue by kitech** [dominikh/go-mode.el#339]
The default height seems too large.
 
This line, 
https://github.com/dominikh/go-mode.el/blob/53c76cddf54638dea5e4cae99ce0181de28e1064/go-mode.el#L1955

**Comment by psanford** [comment]
display-buffer uses a bunch of different heuristics to decide where and how big a window to open. It probably looks different for you than it does for me. Can you share a screenshot of what you are seeing?

**Comment by kitech** [comment]
Default it seems the half of emacs top window heigh

![2020-02-29_14-53_1](https://user-images.githubusercontent.com/24404/75602957-067c6080-5b05-11ea-9215-d145f558390d.png)

Then I set a fixed height argument to `display-buffer` call, this is what I want, but it's better if don't need hard code that height value: `(display-buffer errbuf '(nil (window-height . 6))`

![2020-02-29_14-53](https://user-images.githubusercontent.com/24404/75603037-a4702b00-5b05-11ea-99ba-0eaff4189d15.png)

**Comment by psanford** [comment]
I think there are a couple of options here. 

1. Go mode already has a customizable variable `'gofmt-show-errors` which you can set to 'echo to show output in the echo area instead of creating a separate buffer.
1. Customize `'display-buffer-alist` to get the layout you want. `(display-buffer)` already supports these types of customizations. Something like:

```
(customize-set-variable
 'display-buffer-alist
 '(("\\*Gofmt Errors\\*"
    (display-buffer-below-selected)
    (window-height . fit-window-to-buffer))))
```
