### ISSUE TITLE
Add more syntax highlight

### ISSUE THREAD

**Issue by taigacute** [dominikh/go-mode.el#348]
This is a compare vim with emacs,seems like missed some highlight on emacs.
![image](https://user-images.githubusercontent.com/41671631/77827064-88849700-714e-11ea-8b74-f9ae7ed917eb.png)

**Comment by muirdm** [comment]
I prefer go-mode because it differentiates fields from method calls (but even that doesn't seem very useful). Why is it useful to highlight all fields? What face should be used? We aren't likely to add new syntax highlighting simply to keep highlighting parity with other editors.

Here is how you can add similar highlighting yourself (rerun `go-mode` after evaluating below code):

```elisp
(font-lock-add-keywords 'go-mode
                        `((,(concat "\\.\\(" go-identifier-regexp "\\)") 1 'font-lock-function-name-face)))
```

**Comment by taigacute** [comment]
Ok, i got it.
