### ISSUE TITLE
gofmt: Invalid rcs patch or internal error in go--apply-rcs-patch

### ISSUE THREAD

**Issue by 7ym0n** [dominikh/go-mode.el#407]
call gofmt command report "Invalid rcs patch or internal error in go--apply-rcs-patch" error messge.

**Comment by 7ym0n** [comment]
It's my diff command issue.

**Comment by elimisteve** [comment]
@b40yd Hi there! Can you be more specific please? How did you change your `diff` command so that the `Invalid rcs patch` error would go away?

I'll reply here if I figure it out.

**Comment by elimisteve** [comment]
Got it! I'm using AlpineLinux, and the `diff` command comes from BusyBox instead of wherever it normally comes from on most Linux systems.

The solution on Alpine:

```bash
doas apk add diffutils
```

Thank you [random StackOverflow question](https://stackoverflow.com/questions/63176657/use-gnus-tools-instead-of-busyboxs-for-alpine-image) for inspiring this solution.
