### ISSUE TITLE
go-mode does not correctly highlight Go types

### ISSUE THREAD

**Issue by MatejLach** [dominikh/go-mode.el#51]
Currently, Go types such as int32, float64 etc. are not recognized as part of Go's syntax: 

package main

import "fmt"

func main() {
    var testvar int32 
}

In the above piece of code, 'int32' is not highlighted, even trough it is a valid Go type.
![gomode](https://cloud.githubusercontent.com/assets/531930/3026190/eba27986-e010-11e3-8863-1aea1f3fbbed.png)

**Comment by norbertklar** [comment]
I have this problem too. Please fix it!

**Comment by dominikh** [comment]
Naively highlighting type names is error-prone, because it depends on the context whether an identifier is a type or not.

This really isn't an issue I am intending to fix any time soon. The only correct solution would require using a proper parser, and the complexity of that far outweighs the benefits.

**Comment by norbertklar** [comment]
In vim-go mode, they did a good job: 
![screenshot_2015-07-03_13-24-58](https://cloud.githubusercontent.com/assets/9632419/8498435/db82a84c-2186-11e5-84bc-4e900908311d.png)

**Comment by dominikh** [comment]
How does vim-go render the following piece of code?

```go
package main

func main() {
  int := "hello"
  println(int)
}
```

Also, how does vim-go render the following?

```go
package main

func main() {
	type foo int
	var x foo = 1
	println(x)
}
```

**Comment by norbertklar** [comment]
![screenshot_2015-07-03_14-19-16](https://cloud.githubusercontent.com/assets/9632419/8499034/7e0cab38-218e-11e5-924e-320021e44c8b.png)

![screenshot_2015-07-03_14-19-38](https://cloud.githubusercontent.com/assets/9632419/8499037/825ce752-218e-11e5-83b9-e15f7707f5d6.png)

**Comment by dominikh** [comment]
So vim-go gets both of them wrong, in exactly the ways that make me not implement it that way. 

The first example is harmful, because the syntax highlighting is now wrong and misguiding, potentially hiding errors (you shouldn't be shadowing a built-in type name, because it's bad style, but the bugs it leads to are harder to diagnose if the syntax highlighting is wrong, too).

The second example is harmful because it means that syntax highlighting is only reliable for a subset of types, which also makes it a lot less useful.

(Note to others reading: The second screenshot and my second code snippet show different code. I edited mine after first posting it, my fault. But they show roughly the same issue.)

If you really want such simplistic syntax highlighting for types, you can easily add that yourself, by extending go-mode's fontification table. I won't make it part of go-mode, however.

**Comment by norbertklar** [comment]
I understand the issue, but why hard a such a thing to implement in emacs?

**Comment by dominikh** [comment]
Using vim-go's way would be incredibly easy. Doing it the proper way would require writing a parser for Go code in emacs (although CEDET might help there), which is about as complex as writing a parser in languages other than elisp. However, it would add additional complexity because we'd have to implement fontification ourself, and it would have performance implications (we'd need to parse the buffer every time we'd need to fontify it again).

**Comment by AeroNotix** [comment]
And I believe this go-mode.el was made specifically because the older one tried to implement a parser.

**Comment by dominikh** [comment]
Sort of. The original go-mode had a bastardized version of a "parser" to implement indentation and basic syntax highlighting, but it wasn't working any better (in fact, worse) than Emacs's built-in facilities. It was nowhere close to solving this issue.
